-- AlterTable
ALTER TABLE "Produtor" ADD COLUMN IF NOT EXISTS "avaliacao" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Produtor" ADD COLUMN IF NOT EXISTS "totalAvaliacoes" INTEGER NOT NULL DEFAULT 0;
