-- Adiciona todos os ServiceType faltantes (que existem em constants.ts mas não no enum)
-- e os 3 novos serviços: BIOGAS_RURAL, RASTREABILIDADE, LICENCIAMENTO_AMBIENTAL

ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'ANALISE_SOLO_AVANCADA';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'IRRIGACAO_AUTOMATIZADA';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'APLICACAO_DRONE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'MONITORAMENTO_SATELITE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'AGRICULTURA_PRECISAO';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'TOPOGRAFIA';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'SENSORIAMENTO_REMOTO';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'INSTALACAO_PIVO';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'ENERGIA_SOLAR_RURAL';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'GESTAO_AMBIENTAL';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'REGULARIZACAO_FUNDIARIA';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'CERTIFICACAO_AGRICOLA';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'SEGURANCA_RURAL';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'MANUTENCAO_COLHEITADEIRA';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'TRANSPORTE_GRAOS';
-- Novos serviços
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'BIOGAS_RURAL';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'RASTREABILIDADE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'LICENCIAMENTO_AMBIENTAL';
